import { ICardItem } from '../../types/types';

export const catalog: ICardItem[] = [
    {
        image: 'assets/images/catalog/Batman_socks.jpg',
        name: 'Batman Socks',
        amount: 55,
        year: 2019,
        collection: 'Superhero workdays',
        color: 'pink',
        price: 5,
        size: 40,
        isNew: false,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/Cinderella_socks.jpg',
        name: 'Cinderella Socks',
        amount: 27,
        year: 2022,
        collection: 'Disney princess dream',
        color: 'black',
        price: 7,
        size: 35,
        isNew: true,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/Cozy_blue_socks.jpg',
        name: 'Cozy Socks',
        amount: 89,
        year: 2020,
        collection: 'Warm and cozy',
        color: 'blue',
        price: 7.9,
        size: 38,
        isNew: false,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/Fluffy_white_socks.jpg',
        name: 'Fluffy Socks',
        amount: 31,
        year: 2021,
        collection: 'Warm and cozy',
        color: 'white',
        price: 8,
        size: 37,
        isNew: false,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/Groot_socks.jpg',
        name: 'Groot Socks',
        amount: 11,
        year: 2022,
        collection: 'Superhero workdays',
        color: 'green',
        price: 6,
        size: 41,
        isNew: true,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/HP_black_socks.jpg',
        name: 'Harry Potter Socks',
        amount: 25,
        year: 2019,
        collection: 'Hogwarts school',
        color: 'black',
        price: 4,
        size: 42,
        isNew: false,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/HP_grey_socks.jpg',
        name: 'Harry Potter Socks 2',
        amount: 61,
        year: 2020,
        collection: 'Hogwarts school',
        color: 'grey',
        price: 3,
        size: 35,
        isNew: false,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/HP_purple_socks.jpeg',
        name: 'Harry Potter Socks 3',
        amount: 19,
        year: 2021,
        collection: 'Hogwarts school',
        color: 'purple',
        price: 5.5,
        size: 36,
        isNew: false,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/NY_green.jpg',
        name: 'Christmas Green Socks',
        amount: 24,
        year: 2022,
        collection: 'Christmas morning',
        color: 'green',
        price: 10,
        size: 43,
        isNew: true,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/NY_purple_socks.jpg',
        name: 'Christmas Purple Socks',
        amount: 15,
        year: 2017,
        collection: 'Christmas morning',
        color: 'purple',
        price: 5,
        size: 37,
        isNew: false,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/SB_socks.jpg',
        name: 'Sleeping Beauty Socks',
        amount: 84,
        year: 2022,
        collection: 'Disney princess dream',
        color: 'black',
        price: 7,
        size: 34,
        isNew: true,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/Simple_blue.jpg',
        name: 'Simple Blue Socks',
        amount: 35,
        year: 2019,
        collection: 'Colorful mood',
        color: 'blue',
        price: 6,
        size: 42,
        isNew: false,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/Simple_red_socks.jpg',
        name: 'Simple Red Socks',
        amount: 47,
        year: 2018,
        collection: 'Colorful mood',
        color: 'red',
        price: 3.5,
        size: 36,
        isNew: false,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/Simple_yellow.jpg',
        name: 'Simple Yellow Socks',
        amount: 29,
        year: 2020,
        collection: 'Colorful mood',
        color: 'yellow',
        price: 3.5,
        size: 41,
        isNew: false,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/Snowwhite_socks.jpg',
        name: 'Snow White Socks',
        amount: 38,
        year: 2021,
        collection: 'Disney princess dream',
        color: 'black',
        price: 7,
        size: 38,
        isNew: false,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/NY_red.jpg',
        name: 'Christmas Red Socks',
        amount: 16,
        year: 2016,
        collection: 'Christmas morning',
        color: 'red',
        price: 6,
        size: 43,
        isNew: false,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/summer_grey.jpg',
        name: 'Summer Grey Socks',
        amount: 63,
        year: 2020,
        collection: 'Summer vibes',
        color: 'grey',
        price: 1.5,
        size: 37,
        isNew: false,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/Summer_white.jpg',
        name: 'Summer White Socks',
        amount: 12,
        year: 2021,
        collection: 'Summer vibes',
        color: 'white',
        price: 1,
        size: 35,
        isNew: false,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/Warm_white.jpg',
        name: 'Warm Socks',
        amount: 50,
        year: 2022,
        collection: 'Warm and cozy',
        color: 'white',
        size: 37,
        price: 5,
        isNew: true,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/ww_socks.jpg',
        name: 'Wonder Women Socks',
        amount: 69,
        year: 2022,
        collection: 'Superhero workdays',
        color: 'pink',
        price: 2,
        size: 38,
        isNew: true,
        isChosen: false,
        isHide: false,
    },

    {
        image: 'assets/images/catalog/WW2_socks.jpg',
        name: 'Wonder Women Socks 2',
        amount: 77,
        year: 2014,
        collection: 'Superhero workdays',
        color: 'grey',
        price: 3,
        size: 39,
        isNew: false,
        isChosen: false,
        isHide: false,
    },
];
